---
- name: Set up an httpd webserver
  hosts: aws_ec2
  become: yes
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/aws-key-pair.pem"
    ansible_ssh_user: "ec2-user"

  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Enable EPEL Repository on CentOS 8
      dnf:
        name: epel-release
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

    - name: Enable EPEL Repository on CentOS 7
      yum:
        name: epel-release
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

    - name: Ensure a list of packages installed on CentOS 8
      yum:
        name:
          - firewalld
          - mariadb-server
          - httpd
          - php
          - php-mysqlnd
          - git
          - epel-release
          - python3-pip
          - python3-devel
          - mysql-devel
          - gcc
          - python3-PyMySQL
        state: present
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

    - name: Ensure a list of packages installed on CentOS 7
      yum:
        name:
          - firewalld
          - mariadb-server
          - httpd
          - php
          - php-mysql
          - git
          - epel-release
          - python-pip
          - python-devel
          - mariadb-devel
          - gcc
          - MySQL-python
        state: present
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

    - name: Ensure services are running
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - mariadb

    - name: Configure firewall for Database
      command: "{{ item }}"
      loop:
        - firewall-cmd --permanent --zone=public --add-port=3306/tcp
        - firewall-cmd --reload

    - name: Clone repository to /var/www/html/
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html/
        force: true

    - name: Ensure the 'test' database does not exist
      mysql_db:
        name: test
        state: absent

    - name: Create a new database 'ecomdb'
      mysql_db:
        name: ecomdb
        state: present
      notify:
        - Import db-load-script.sql

    - name: Create a new MySQL user 'ecomuser'
      mysql_user:
        name: ecomuser
        host: localhost
        password: ecompassword
        priv: '*.*:ALL'
        state: present

    - name: Configure firewall for Web
      command: "{{ item }}"
      loop:
        - firewall-cmd --permanent --zone=public --add-port=80/tcp
        - firewall-cmd --reload

    - name: Change DirectoryIndex in httpd.conf to use index.php
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "DirectoryIndex index.html"
        replace: "DirectoryIndex index.php"

    - name: Ensure httpd service is running
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Replace IP address in index.php to localhost
      replace:
        path: /var/www/html/index.php
        regexp: '172.20.1.101'
        replace: 'localhost'

  handlers:
    - name: Import db-load-script.sql
      mysql_db:
        state: import
        name: ecomdb
        target: /var/www/html/assets/db-load-script.sql
