- name: This sets up an httpd webserver
  hosts: aws_ec2
  become: yes
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/aws-key-pair.pem"  
    ansible_ssh_user: "ec2-user"
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
        update_cache: yes

    - name: Start and enable Apache service
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Create web root directory
      file:
        path: /var/www/html
        state: directory
        owner: apache
        group: apache
        mode: '0755'

    - name: Create a simple index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome to My Website</title>
          </head>
          <body>
              <h1>Hello World!</h1>
              <p>This is a simple static website served by Apache.</p>
          </body>
          </html>
        owner: apache
        group: apache
        mode: '0644'

    - name: Allow HTTP traffic through the firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Ensure firewall is running
      systemd:
        name: firewalld
        state: started
        enabled: yes